[profile.default]
src = "src"
out = "out"
libs = ["lib"]

fs_permissions = [{ access = "write", path = "./artifacts" }]

evm_version = "cancun"
optimizer = true
optimizer-runs = 200
solc = "0.8.28"
via_ir = false
