[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read", path = "./script" }]
# evm_version = "cancun"
optimizer = true
optimizer-runs = 200
solc = "0.8.17"
via_ir = false
